In [38]:
import requests
from bs4 import BeautifulSoup
import csv

html_doc = requests.get('https://www.worldometers.info/coronavirus/')
soup = BeautifulSoup(html_doc.content, 'html.parser')

table_content = soup.find('table')

table_head = table_content.find('thead')
table_body = table_content.find('tbody')
table_row = table_body.find_all('tr')
headerrow=table_head.find_all('th')
headers_list = [th.text.strip() for th in headerrow]

file=open("yoniy12345679.csv",'w',newline='',encoding='utf-8')
write= csv.writer(file)
write.writerow(headers_list)
# data_rows = []
for row in table_row[8:]:
    cols = row.find_all('td')
    
    # Clean each cell: strip whitespace, remove newlines but keep commas inside numbers
    # cleaned_cells = [col.text.strip() for col in cols]
    # data_rows.append(cleaned_cells)
    data_rows = []
    for col in cols:
        data_rows.append(col.text.strip().replace(",",""))
       
       
    write.writerow(data_rows)
        
    # write.writerow(cleaned_cells)

file.close()    
print("hello")

hello

In [39]:
import pandas as pd
df = pd.read_csv('yoniy12345679.csv')

In [40]:
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,1,USA,111820082,NaN,1219487.0,NaN,109814428.0,NaN,786167.0,940.0,...,1.186852e+09,3544901.0,3.348053e+08,North America,3.0,275.0,0.0,NaN,NaN,2348.0
1,2,India,45035393,NaN,533570.0,NaN,NaN,NaN,NaN,NaN,...,9.358795e+08,665334.0,1.406632e+09,Asia,31.0,2636.0,2.0,NaN,NaN,0.4
2,3,France,40138560,NaN,167642.0,NaN,39970918.0,NaN,0.0,NaN,...,2.714902e+08,4139547.0,6.558452e+07,Europe,2.0,391.0,0.0,NaN,NaN,NaN
3,4,Germany,38828995,NaN,183027.0,NaN,38240600.0,NaN,405368.0,NaN,...,1.223324e+08,1458359.0,8.388360e+07,Europe,2.0,458.0,1.0,NaN,NaN,4833.0
4,5,Brazil,38743918,NaN,711380.0,NaN,36249161.0,NaN,1783377.0,NaN,...,6.377617e+07,296146.0,2.153536e+08,South America,6.0,303.0,3.0,NaN,NaN,8281.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,227,Tokelau,80,NaN,NaN,NaN,NaN,NaN,80.0,NaN,...,NaN,NaN,1.378000e+03,Australia/Oceania,17.0,NaN,NaN,NaN,NaN,58055.0
227,228,Vatican City,29,NaN,NaN,NaN,29.0,NaN,0.0,NaN,...,NaN,NaN,7.990000e+02,Europe,28.0,NaN,NaN,NaN,NaN,NaN
228,229,Western Sahara,10,NaN,1.0,NaN,9.0,NaN,0.0,NaN,...,NaN,NaN,6.261610e+05,Africa,62616.0,626161.0,NaN,NaN,NaN,NaN
229,230,MS Zaandam,9,NaN,2.0,NaN,7.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,231,China,503302,NaN,5272.0,NaN,379053.0,NaN,118977.0,NaN,...,1.600000e+08,110461.0,1.448471e+09,Asia,2878.0,274748.0,9.0,NaN,NaN,82.0

In [41]:
df.ActiveCases

0       786167.0
1            NaN
2            0.0
3       405368.0
4      1783377.0
         ...
226         80.0
227          0.0
228          0.0
229          0.0
230     118977.0
Name: ActiveCases, Length: 231, dtype: float64

In [6]:
df[df["Country,Other"]=="USA"]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,1,USA,111820082,NaN,1219487.0,NaN,109814428.0,NaN,786167.0,940.0,...,1.186852e+09,3544901.0,334805269.0,North America,3.0,275.0,0.0,NaN,NaN,2348.0

In [5]:
df[df.Continent=="Asia"]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
1,2,India,45035393,NaN,533570.0,NaN,NaN,NaN,NaN,NaN,...,935879495.0,665334.0,1.406632e+09,Asia,31.0,2636.0,2.0,NaN,NaN,0.40
5,6,S. Korea,34571873,NaN,35934.0,NaN,34535939.0,NaN,0.0,NaN,...,15804065.0,307892.0,5.132990e+07,Asia,1.0,1428.0,3.0,NaN,NaN,NaN
6,7,Japan,33803572,NaN,74694.0,NaN,NaN,NaN,NaN,NaN,...,100414883.0,799578.0,1.255848e+08,Asia,4.0,1681.0,1.0,NaN,NaN,95582.00
10,11,Turkey,17232066,NaN,102174.0,NaN,NaN,NaN,NaN,NaN,...,162743369.0,1902052.0,8.556198e+07,Asia,5.0,837.0,1.0,NaN,NaN,4024.00
13,14,Vietnam,11625195,NaN,43206.0,NaN,10640971.0,NaN,941018.0,NaN,...,85826548.0,867342.0,9.895354e+07,Asia,9.0,2290.0,1.0,NaN,NaN,9510.00
14,15,Taiwan,10241523,NaN,19005.0,NaN,10222518.0,NaN,0.0,NaN,...,30742304.0,1286903.0,2.388860e+07,Asia,2.0,1257.0,1.0,NaN,NaN,NaN
18,19,Iran,7627186,NaN,146811.0,NaN,NaN,NaN,NaN,NaN,...,57320267.0,666338.0,8.602284e+07,Asia,11.0,586.0,2.0,NaN,NaN,1199.00
19,20,Indonesia,6829221,NaN,162063.0,NaN,6647104.0,NaN,20054.0,NaN,...,114158919.0,408975.0,2.791345e+08,Asia,41.0,1722.0,2.0,NaN,NaN,72.00
27,28,Malaysia,5278406,NaN,37348.0,NaN,5233268.0,NaN,7790.0,11.0,...,68580916.0,2066869.0,3.318107e+07,Asia,6.0,888.0,0.0,NaN,NaN,235.00
30,31,Israel,4841772,NaN,12707.0,NaN,4798473.0,NaN,30592.0,NaN,...,41373364.0,4436346.0,9.326000e+06,Asia,2.0,734.0,0.0,NaN,NaN,3280.00
31,32,DPRK,4772813,NaN,74.0,NaN,4772739.0,NaN,0.0,NaN,...,NaN,NaN,2.599068e+07,Asia,5.0,351225.0,NaN,NaN,NaN,NaN
32,33,Thailand,4770149,NaN,34586.0,NaN,4692636.0,NaN,42927.0,NaN,...,17273454.0,246488.0,7.007820e+07,Asia,15.0,2026.0,4.0,NaN,NaN,613.00
36,37,Philippines,4140383,NaN,66864.0,NaN,4067381.0,NaN,6138.0,NaN,...,36102746.0,320888.0,1.125090e+08,Asia,27.0,1683.0,3.0,NaN,NaN,55.00
40,41,Singapore,3006155,NaN,2024.0,NaN,3004131.0,NaN,0.0,4.0,...,24756666.0,4165302.0,5.943546e+06,Asia,2.0,2937.0,0.0,NaN,NaN,NaN
41,42,Hong Kong,2937609,NaN,14924.0,NaN,2916005.0,NaN,6680.0,NaN,...,76127725.0,10011143.0,7.604299e+06,Asia,3.0,510.0,0.0,NaN,NaN,878.00
45,46,Iraq,2465545,NaN,25375.0,NaN,2439497.0,NaN,673.0,NaN,...,19544451.0,463523.0,4.216496e+07,Asia,17.0,1662.0,2.0,NaN,NaN,16.00
47,48,Bangladesh,2049377,NaN,29493.0,NaN,NaN,NaN,NaN,NaN,...,15254399.0,90862.0,1.678857e+08,Asia,82.0,5692.0,11.0,NaN,NaN,-168.58
49,50,Georgia,1861665,NaN,17132.0,NaN,NaN,NaN,NaN,NaN,...,16920079.0,4263340.0,3.968738e+06,Asia,2.0,232.0,0.0,NaN,NaN,17130.00
50,51,Jordan,1746997,NaN,14122.0,NaN,1731007.0,NaN,1868.0,59.0,...,17201885.0,1669945.0,1.030087e+07,Asia,6.0,729.0,1.0,NaN,NaN,181.00
52,53,Pakistan,1581936,NaN,30664.0,NaN,1538689.0,NaN,12583.0,NaN,...,30589153.0,133292.0,2.294890e+08,Asia,145.0,7484.0,8.0,NaN,NaN,55.00
55,56,Kazakhstan,1411831,NaN,13848.0,NaN,1383020.0,NaN,14963.0,24.0,...,11575012.0,602707.0,1.920504e+07,Asia,14.0,1387.0,2.0,NaN,NaN,779.00
62,63,Lebanon,1243838,NaN,10952.0,NaN,1087587.0,NaN,145299.0,74.0,...,4795578.0,717380.0,6.684849e+06,Asia,5.0,610.0,1.0,NaN,NaN,21736.00
68,69,UAE,1067030,NaN,2349.0,NaN,NaN,NaN,NaN,NaN,...,200732262.0,19910389.0,1.008178e+07,Asia,9.0,4292.0,0.0,NaN,NaN,1007.00
71,72,Mongolia,1011496,NaN,2284.0,NaN,1009212.0,NaN,0.0,NaN,...,4030048.0,1193000.0,3.378078e+06,Asia,3.0,1479.0,1.0,NaN,NaN,NaN
72,73,Nepal,1003450,NaN,12031.0,NaN,991322.0,NaN,97.0,NaN,...,6047766.0,200088.0,3.022558e+07,Asia,30.0,2512.0,5.0,NaN,NaN,3.00
75,76,Saudi Arabia,841469,NaN,9646.0,NaN,NaN,NaN,NaN,NaN,...,45481735.0,1268848.0,3.584491e+07,Asia,43.0,3716.0,1.0,NaN,NaN,109.00
77,78,Azerbaijan,835234,NaN,10400.0,NaN,824089.0,NaN,745.0,NaN,...,7748050.0,752223.0,1.030020e+07,Asia,12.0,990.0,1.0,NaN,NaN,72.00
78,79,Bahrain,729549,NaN,1574.0,NaN,727915.0,NaN,60.0,NaN,...,10948549.0,6137138.0,1.783983e+06,Asia,2.0,1133.0,0.0,NaN,NaN,34.00
79,80,Cyprus,681110,NaN,1365.0,NaN,679745.0,NaN,0.0,NaN,...,9640118.0,7879860.0,1.223387e+06,Asia,2.0,896.0,0.0,NaN,NaN,NaN
81,82,Sri Lanka,672754,NaN,16897.0,NaN,655852.0,NaN,5.0,NaN,...,6486117.0,300619.0,2.157584e+07,Asia,32.0,1277.0,3.0,NaN,NaN,0.20
82,83,Kuwait,667158,NaN,2570.0,NaN,NaN,NaN,NaN,NaN,...,8455743.0,1930391.0,4.380326e+06,Asia,7.0,1704.0,1.0,NaN,NaN,993.00
83,84,Myanmar,641873,NaN,19495.0,NaN,620159.0,NaN,2219.0,NaN,...,11711514.0,212061.0,5.522714e+07,Asia,86.0,2833.0,5.0,NaN,NaN,40.00
86,87,Palestine,621008,NaN,5404.0,NaN,615445.0,NaN,159.0,NaN,...,3078533.0,575907.0,5.345541e+06,Asia,9.0,989.0,2.0,NaN,NaN,30.00
89,90,Qatar,514524,NaN,690.0,NaN,513687.0,NaN,147.0,16.0,...,4065369.0,1364257.0,2.979915e+06,Asia,6.0,4319.0,1.0,NaN,NaN,49.00
94,95,Armenia,451831,NaN,8777.0,NaN,435162.0,NaN,7892.0,NaN,...,3242901.0,1091164.0,2.971966e+06,Asia,7.0,339.0,1.0,NaN,NaN,2655.00
96,97,Oman,399449,NaN,4628.0,NaN,NaN,NaN,NaN,NaN,...,25000000.0,4695724.0,5.323993e+06,Asia,13.0,1150.0,0.0,NaN,NaN,1907.00
101,102,Brunei,343719,NaN,225.0,NaN,243601.0,NaN,99893.0,3.0,...,717784.0,1611437.0,4.454310e+05,Asia,1.0,1980.0,1.0,NaN,NaN,224261.00
108,109,Uzbekistan,253662,NaN,1637.0,NaN,241486.0,NaN,10539.0,23.0,...,1377915.0,40077.0,3.438208e+07,Asia,136.0,21003.0,25.0,NaN,NaN,307.00
109,110,Afghanistan,234174,NaN,7996.0,NaN,211080.0,NaN,15098.0,NaN,...,1390730.0,34125.0,4.075439e+07,Asia,174.0,5097.0,29.0,NaN,NaN,370.00
112,113,Laos,218970,NaN,758.0,NaN,NaN,NaN,NaN,NaN,...,1233207.0,164845.0,7.481023e+06,Asia,34.0,9869.0,6.0,NaN,NaN,28145.00
114,115,Kyrgyzstan,206897,NaN,2991.0,NaN,196406.0,NaN,7500.0,131.0,...,1907195.0,283460.0,6.728271e+06,Asia,33.0,2250.0,4.0,NaN,NaN,1115.00
118,119,Maldives,186694,NaN,316.0,NaN,163687.0,NaN,22691.0,25.0,...,2213831.0,4092223.0,5.409850e+05,Asia,3.0,1712.0,0.0,NaN,NaN,41944.00
123,124,Cambodia,139103,NaN,3056.0,NaN,136044.0,NaN,3.0,NaN,...,3091420.0,180062.0,1.716864e+07,Asia,123.0,5618.0,6.0,NaN,NaN,0.20
146,147,Bhutan,62697,NaN,21.0,NaN,61564.0,NaN,1112.0,NaN,...,2303734.0,2923739.0,7.879410e+05,Asia,13.0,37521.0,0.0,NaN,NaN,1411.00
147,148,Syria,57743,NaN,3165.0,NaN,54578.0,NaN,0.0,NaN,...,146269.0,7553.0,1.936481e+07,Asia,335.0,6118.0,132.0,NaN,NaN,NaN
169,170,Macao,27673,NaN,123.0,NaN,3487.0,NaN,24063.0,NaN,...,7850.0,11760.0,6.674900e+05,Asia,24.0,5427.0,85.0,NaN,NaN,36050.00
175,176,Timor-Leste,23460,NaN,138.0,NaN,23102.0,NaN,220.0,NaN,...,278529.0,203391.0,1.369429e+06,Asia,58.0,9923.0,5.0,NaN,NaN,161.00
183,184,Tajikistan,17786,NaN,125.0,NaN,17264.0,NaN,397.0,NaN,...,NaN,NaN,9.957464e+06,Asia,560.0,79660.0,NaN,NaN,NaN,40.00
196,197,Yemen,11945,NaN,2159.0,NaN,9124.0,NaN,662.0,NaN,...,329592.0,10579.0,3.115487e+07,Asia,2608.0,14430.0,95.0,NaN,NaN,21.00
230,231,China,503302,NaN,5272.0,NaN,379053.0,NaN,118977.0,NaN,...,160000000.0,110461.0,1.448471e+09,Asia,2878.0,274748.0,9.0,NaN,NaN,82.00

In [13]:
total_sum = df.TotalCases.sum()
print(total_sum)

704753890

In [42]:
df[(df.TotalCases==503302) &(df.TotalDeaths==5272.0)	]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
230,231,China,503302,NaN,5272.0,NaN,379053.0,NaN,118977.0,NaN,...,160000000.0,110461.0,1.448471e+09,Asia,2878.0,274748.0,9.0,NaN,NaN,82.0

In [44]:
df[df["Country,Other"].str.contains("z")]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
4,5,Brazil,38743918,NaN,711380.0,NaN,36249161.0,NaN,1783377.0,NaN,...,63776166.0,296146.0,215353593.0,South America,6.0,303.0,3.0,NaN,NaN,8281.0
33,34,Czechia,4759041,NaN,43517.0,NaN,4715206.0,NaN,318.0,2.0,...,57834241.0,5386552.0,10736784.0,Europe,2.0,247.0,0.0,NaN,NaN,30.0
35,36,Switzerland,4453053,NaN,14452.0,NaN,4438309.0,NaN,292.0,NaN,...,23833472.0,2716487.0,8773637.0,Europe,2.0,607.0,0.0,NaN,NaN,33.0
55,56,Kazakhstan,1411831,NaN,13848.0,NaN,1383020.0,NaN,14963.0,24.0,...,11575012.0,602707.0,19205043.0,Asia,14.0,1387.0,2.0,NaN,NaN,779.0
77,78,Azerbaijan,835234,NaN,10400.0,NaN,824089.0,NaN,745.0,NaN,...,7748050.0,752223.0,10300205.0,Asia,12.0,990.0,1.0,NaN,NaN,72.0
87,88,Venezuela,552695,NaN,5856.0,NaN,546537.0,NaN,302.0,31.0,...,3359014.0,114771.0,29266991.0,South America,53.0,4998.0,9.0,NaN,NaN,10.0
95,96,Bosnia and Herzegovina,403615,NaN,16388.0,NaN,379084.0,NaN,8143.0,NaN,...,1884721.0,580036.0,3249317.0,Europe,8.0,198.0,2.0,NaN,NaN,2506.0
108,109,Uzbekistan,253662,NaN,1637.0,NaN,241486.0,NaN,10539.0,23.0,...,1377915.0,40077.0,34382084.0,Asia,136.0,21003.0,25.0,NaN,NaN,307.0
110,111,Mozambique,233731,NaN,2250.0,NaN,228805.0,NaN,2676.0,11.0,...,1371127.0,41437.0,33089461.0,Africa,142.0,14706.0,24.0,NaN,NaN,81.0
114,115,Kyrgyzstan,206897,NaN,2991.0,NaN,196406.0,NaN,7500.0,131.0,...,1907195.0,283460.0,6728271.0,Asia,33.0,2250.0,4.0,NaN,NaN,1115.0
140,141,Belize,71409,NaN,688.0,NaN,NaN,NaN,NaN,NaN,...,576016.0,1397453.0,412190.0,North America,6.0,599.0,1.0,NaN,NaN,1543.0
155,156,Tanzania,43223,NaN,846.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,63298550.0,Africa,1464.0,74821.0,NaN,NaN,NaN,667.0

In [49]:
df[df["Country,Other"].str.startswith("B") & df["Country,Other"].str.contains("z")]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
4,5,Brazil,38743918,NaN,711380.0,NaN,36249161.0,NaN,1783377.0,NaN,...,63776166.0,296146.0,215353593.0,South America,6.0,303.0,3.0,NaN,NaN,8281.0
95,96,Bosnia and Herzegovina,403615,NaN,16388.0,NaN,379084.0,NaN,8143.0,NaN,...,1884721.0,580036.0,3249317.0,Europe,8.0,198.0,2.0,NaN,NaN,2506.0
140,141,Belize,71409,NaN,688.0,NaN,NaN,NaN,NaN,NaN,...,576016.0,1397453.0,412190.0,North America,6.0,599.0,1.0,NaN,NaN,1543.0

In [48]:
df[df["Country,Other"].str.endswith("a")]

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/\n1M pop,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
1,2,India,45035393,NaN,533570.0,NaN,NaN,NaN,NaN,NaN,...,935879495.0,665334.0,1.406632e+09,Asia,31.0,2636.0,2.0,NaN,NaN,0.4
5,6,S. Korea,34571873,NaN,35934.0,NaN,34535939.0,NaN,0.0,NaN,...,15804065.0,307892.0,5.132990e+07,Asia,1.0,1428.0,3.0,NaN,NaN,NaN
9,10,Russia,24124215,NaN,402756.0,NaN,23545818.0,NaN,175641.0,NaN,...,273400000.0,1875095.0,1.458059e+08,Europe,6.0,362.0,1.0,NaN,NaN,1205.0
12,13,Australia,11853144,NaN,24414.0,NaN,11820014.0,NaN,8716.0,3.0,...,81916639.0,3142326.0,2.606879e+07,Australia/Oceania,2.0,1068.0,0.0,NaN,NaN,334.0
15,16,Argentina,10128845,NaN,130841.0,NaN,9997258.0,NaN,746.0,NaN,...,35716069.0,776264.0,4.601023e+07,South America,5.0,352.0,1.0,NaN,NaN,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,218,Anguilla,3904,NaN,12.0,NaN,NaN,NaN,NaN,NaN,...,51382.0,3373736.0,1.523000e+04,North America,4.0,1269.0,0.0,NaN,NaN,854.0
218,219,Wallis and Futuna,3550,NaN,8.0,NaN,438.0,NaN,3104.0,NaN,...,20508.0,1867419.0,1.098200e+04,Australia/Oceania,3.0,1373.0,1.0,NaN,NaN,282644.0
221,222,Saint Helena,2166,NaN,NaN,NaN,2.0,NaN,2164.0,NaN,...,NaN,NaN,6.115000e+03,Africa,3.0,NaN,NaN,NaN,NaN,353884.0
228,229,Western Sahara,10,NaN,1.0,NaN,9.0,NaN,0.0,NaN,...,NaN,NaN,6.261610e+05,Africa,62616.0,626161.0,NaN,NaN,NaN,NaN
230,231,China,503302,NaN,5272.0,NaN,379053.0,NaN,118977.0,NaN,...,160000000.0,110461.0,1.448471e+09,Asia,2878.0,274748.0,9.0,NaN,NaN,82.0